# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home
email: james dot jia at berkeley dot edu
description: > # this means to ignore newlines until "baseurl:"
  James Jia's website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamesjia.com" # the base hostname & protocol for your site
github_username:  jamesjia94
timezone: America/Los_Angeles

# Build settings
markdown: kramdown

# Set anchor_prefix to "/" so sidebar works for all pages other than index.
defaults:
- scope:
    path: ""
  values:
    anchor_prefix: "/"